use_frameworks!
platform :ios, '10.0'

target 'HMRRangeSlider_Example' do
  pod 'HMRRangeSlider', :path => '../'
end

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
